name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Configure Git email/username
        run: |
          git config --global user.email "orta+dangersystems@artsy.net"
          git config --global user.name "Danger.Systems"

      - name: Linting
        run: bundle exec rubocop

      - name: Running Tests
        run: bundle exec rake spec

      - name: Running the Dangerfile for this repo
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNNING_IN_ACTIONS: true
        run: bundle exec danger --verbose
